leap year
Subhransupanda2000/jspider-code pull request #1
Opened 2024-05-31 17:17 UTC by Subhransupanda2000

2024-05-31 18:01 UTC, rkpatra201 requested changes

2024-05-31 18:01 UTC, rkpatra201 commented on src/main/java/com/example/jspiderjava/MapExample.java
> +        ConcurrentHashMap ch=new ConcurrentHashMap<>();
Why we used concurrenthashmap instead hashmap

2024-05-31 18:01 UTC, rkpatra201 commented on src/main/java/com/example/jspiderjava/ReverseString.java
> +        sb.reverse();
How to reverse a string without using loop or above method

2024-06-02 07:08 UTC, Subhransupanda2000 commented on src/main/java/com/example/jspiderjava/MapExample.java
> +        ConcurrentHashMap ch=new ConcurrentHashMap<>();
Hashmap is not thread safe . If we will make it threadsafe its perfomance will go down. concurrenthasmap solving all this using  16 boquite approach

2024-06-02 07:10 UTC, Subhransupanda2000 commented on src/main/java/com/example/jspiderjava/ReverseString.java
> +        sb.reverse();
I have added that in this pr

2024-06-02 07:14 UTC, rkpatra201 commented on src/main/java/com/example/jspiderjava/MapExample.java
> +        ConcurrentHashMap ch=new ConcurrentHashMap<>();
But here your code is running in single thread and always thread safe

2024-06-02 07:14 UTC, rkpatra201 requested changes
Ok

2024-06-03 01:07 UTC, rkpatra201 requested changes

2024-06-03 01:07 UTC, rkpatra201 commented on src/main/java/com/example/jspiderjava/ReverseStringMethod2.java
> +        while (left < right) {
This is loop using while

2024-06-03 03:33 UTC, merged